import{i as c,S as m}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();function p(){const r=inputSearch.value.trim().split(",").join("+"),s=new URLSearchParams({key:"42959666-b225ac6c9c40b570269fe0b4e",q:[r],image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${s}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function d(r){if(r.length==0)c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",progressBarColor:"#FFFFFF",icon:null,backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff"});else{const s=r.map(e=>`<li class="image-item">
          <a class="image-link" href="${e.largeImageURL}">
          <img class="image" src="${e.webformatURL}" alt="${e.tags}" />
          </a>
          <ul class="image-information-box">
          <li class="item-information"><p><span class="info-title">Likes</span></br>${e.likes}</p></li>
          <li class="item-information"><p><span class="info-title">Views</span></br>${e.views}</p></li>
          <li class="item-information"><p><span class="info-title">Comments</span></br>${e.comments}</p></li>
          <li class="item-information"><p><span class="info-title">Downloads</span></br>${e.downloads}</p></li>
          </ul>
          </li >`).join("");f.insertAdjacentHTML("beforeend",s),h.refresh()}}const i=document.querySelector(".search-form");i.elements.search;const f=document.querySelector(".gallery"),h=new m(".gallery a",{captionsData:"alt",captionDelay:300}),u=document.querySelector(".loader");u.style.display="none";const l=()=>{u.style.display="none"};i.addEventListener("submit",g);function g(r){r.preventDefault(),f.innerHTML="",r.target.elements.search.value.trim()!==""&&(window.onload=()=>{p().then(e=>{d(e.hits),l()}).catch(e=>{console.log(e),l(),c.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight",icon:null,backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff"})})},window.onload(),i.reset())}
//# sourceMappingURL=commonHelpers.js.map
